### PR TITLE
Allow to configure Agora through AGORA_ENDPOINT

### PR DESCRIPTION
**Pull request by Geod24**
@MichaelKim20 @TrustHenry : Haven't tested it yet, does this make sense to you ?

Part of #106

### CODE REVIEW

**Comment by TrustHenry** [comment]
https://github.com/bpfkorea/stoa/blob/bc32eef0f76d0df113596bdcd504abb13c656c65/src/Stoa.ts#L86
I think it should be reflected here as well.

**Comment by Geod24** [comment]
> I think it should be reflected here as well.

I'm not sure what is the intended meaning of this field. In my case, I am only interested in changing the port, so I altered the PR.

**Review by TrustHenry — APPROVED** [review]
LGTM

**Comment by MichaelKim20** [comment]
I execute command.
export AGORA_ENDPOINT=http://127.0.0.1:2827
outputs logs:
URL {
  href: 'http://127.0.0.1:2827/',
  origin: 'http://127.0.0.1:2827',
  protocol: 'http:',
  username: '',
  password: '',
  host: '127.0.0.1:2827',
  hostname: '127.0.0.1',
  port: '2827',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}

I checked that it was going well.

**Review by MichaelKim20 — APPROVED** [review]
LGTM

**Pull request merged**
