### PR TITLE
Add block timestamp to block header

### PR DESCRIPTION
**Pull request by TrustHenry**
Upgrade SDK to 0.0.13
Tests changes and due to the addition of type timestamp in the block header.

### CODE REVIEW

**Comment by TrustHenry** [comment]
It was closed due to @MichaelKim20's mistake, open it again.

**Comment by TrustHenry** [comment]
Cause of Docker Build Error

```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@14.15.4 (node-v83 ABI, musl) (falling back to source compile with node-gyp)
```

**Comment by TrustHenry** [comment]
https://github.com/mapbox/node-sqlite3/issues/1424

Try with `sqlite3@5.0.0`

**Comment by TrustHenry** [comment]
https://github.com/bpfkorea/stoa/blob/9e40408e0c72b1b0b530209d786d88bb07a7e3e8/package-lock.json#L2359-L2367

**Comment by TrustHenry** [comment]
It's Green.

**Review by MichaelKim20 — APPROVED** [review]
Very good.

**Pull request merged**
