### PR TITLE
Upgrade npm modules

### PR DESCRIPTION
**Pull request by MichaelKim20**
I upgraded Node.js to v14.14.0
And the folder `npm_modules` were erased and newly installed.
Then the following error came out.
```
> sqlite3@4.2.0 install /Users/mukeunkim/Work/WorkSpace_BPFK/stoa_docker/stoa/bin/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.14.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 

```
And I upgraded sqlite3, and all the modules were installed normally.
I also upgraded other npm modules.

### CODE REVIEW

**Comment by Geod24** [comment]
```
  Test for storing block data in the database
    ✓ Error-handling test when writing a transaction.
    ✓ Error-handling test when writing a enrollment.
    ✓ Error-handling test when writing a block.
Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 139
```

:|

**Comment by MichaelKim20** [comment]
I checked that the error occurred in SQLite3.

**Comment by TrustHenry** [comment]
> I checked that the error occurred in SQLite3.

https://github.com/bpfkorea/stoa/pull/147
Does this PR solve the problem?

**Review by TrustHenry — APPROVED** [review]
Nice!
node 14 & 15 version & sqlite3: 5.0.0
Test all passed

**Comment by TrustHenry** [comment]
If there is no problem with upgrading the version, I will merge it.

**Pull request merged**
