### PR TITLE
Fix the validators get query

### PR DESCRIPTION
**Pull request by TrustHenry**
Added height to group criteria in validators query.

### CODE REVIEW

**Comment by MichaelKim20** [comment]
@TrustHenry 
If the block height is 20 or higher, the following PreImage values are a bit strange. Please check it out.

**Comment by TrustHenry** [comment]
> @TrustHenry
> If the block height is 20 or higher, the following PreImage values are a bit strange. Please check it out.
> 
> 

It's because the pre-images have not been released.
I think that should be dealt with as a different issue.

**Comment by MichaelKim20** [comment]
Agora delivers pre-image to block height 18. After that, there is no pre-image received. Don't know why.

**Comment by TrustHenry** [comment]
> Agora delivers pre-image to block height 18. After that, there is no pre-image received. Don't know why.

yes!

**Review by MichaelKim20 — APPROVED** [review]
Endpoint `/validators` now operate normally at block heights above 20.

**Pull request merged**
