### PR TITLE
Add .dockerignore for removing logs, docs, database, ...

### LINKED ISSUE #111: We need a `.dockerignore`
To ignore folders and files that are not needed to create a docker image.

### PR DESCRIPTION
**Pull request by MichaelKim20**
I added the list below to ignore folders and files that are not needed to create a docker image.
node_modules
docs
logs
database
.vscode
.github
.idea

### CODE REVIEW

**Comment by MichaelKim20** [comment]
Below is a log that was recorded internally after the docker was executed.

[Stoa] 2020-10-07T04:32:52.849Z info Stoa API server listening at 3836

**Comment by Geod24** [comment]
Need to add a trailing slash (`/`) otherwise 👍

**Comment by Geod24** [comment]
> Below is a log that was recorded internally after the docker was executed.

I'm not sure I follow. The `.dockerignore` is only used when building the container, so a log of the run is a bit too late.
By the way, isn't `node_modules` required to run the app ?

**Comment by MichaelKim20** [comment]
> > Below is a log that was recorded internally after the docker was executed.
> 
> I'm not sure I follow. The `.dockerignore` is only used when building the container, so a log of the run is a bit too late.
> By the way, isn't `node_modules` required to run the app ?

The node_modules will be reinstalled by the command below.
RUN npm ci

**Comment by MichaelKim20** [comment]
> Need to add a trailing slash (`/`) otherwise 👍

 I fixed it

**Review by TrustHenry — APPROVED** [review]
Required when building a docker image, but good if you test it often.

**Comment by MichaelKim20** [comment]
I made the following changes.
I also added .git.
```
# Part of the source tree, but not needed to build Stoa
.git/
.github/
docs/
logs/

# Dependency build files, It is installed when creating a docker image.
node_modules/

# Database file
database

# Visual Studio Code
.vscode/

# WebStorm
.idea/
```

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
