### PR TITLE
Apply a class BitMask in the BlockerHeader

### PR DESCRIPTION
**Pull request by MichaelKim20**
This was made to adapt to changes in Agora.
https://github.com/bosagora/agora/pull/2210/files

### CODE REVIEW

**Comment by MichaelKim20** [comment]
I will start the review after the issue below is resolved.
https://github.com/bosagora/agora/issues/2259

**Comment by MichaelKim20** [comment]
I tested using the latest version of Agora.
It confirmed that blocks, transactions, and pre-images were received.
I confirmed that all of this was handled correctly.

**Review by TrustHenry — APPROVED** [review]
LGTM

**Comment by MichaelKim20** [comment]
Thank you

**Pull request merged**
