### PR TITLE
Apply the hash value according to the `BlockHead` change

### PR DESCRIPTION
**Pull request by MichaelKim20**
Slashing information was recently added to Agora's Block Header.
I apply the change to Stoa for this.

I extracted block data from Agora with JSON. And we provide it through the link below.
https://gist.github.com/MichaelKim20/be432a180793e7a901801b4d98ac5848
I changed the test code based on this.

Relates to #234

### CODE REVIEW

**Comment by MichaelKim20** [comment]
The lockfileVersion is excluded because it is constantly set to 1 when the PR Bump is merged.

**Review by TrustHenry — APPROVED** [review]
LGTM

**Comment by Geod24** [comment]
This broke the Docker build.

**Comment by Geod24** [comment]
https://hub.docker.com/repository/registry-1.docker.io/bpfk/stoa/builds/0e1c1896-7a20-4657-8ba4-2b6334b17152

**Pull request merged**
