### PR TITLE
Agora changed the endpoint parameter from block_height to height

### LINKED ISSUE #315: Agora changed the endpoint parameter from block_height to height
Agora's sudden change to the Endpoint interface can cause the STOA to stop.
Endpoints affected STOA by changing Agora.
`GET /blocks_from`
`GET /merkle_path`

https://github.com/bosagora/agora/pull/1909

### PR DESCRIPTION
**Pull request by TrustHenry**
Agora changed the API endpoint parameter name.

Related to https://github.com/bosagora/agora/pull/1909
https://github.com/bosagora/stoa/issues/315

### CODE REVIEW

**Review by kchulj — APPROVED** [review]
🟢

**Review by hewison-chris — APPROVED** [review]
LGTM, sorry I should have warned you of this change.

**Comment by TrustHenry** [comment]
Thank you for the review!

**Comment by MichaelKim20** [comment]
Nice!

**Pull request merged**
